use crate::notifications::DownloadNotifications;
use std::io::{Read, Seek, Write};
use std::path::{Path, PathBuf};

pub(super) const STAGING_ROOT_NAME: &str = ".nuclear-downloader-staging";
pub(super) const STAGING_MARKER_NAME: &str = ".nuclear-downloader-owner-v1.json";
const STAGING_CLEANUP_PREFIX: &str = ".cleanup-";
const MAX_STAGING_MARKER_BYTES: u64 = 4 * 1024;

#[cfg(test)]
type MarkerInitializationHook = Box<dyn FnOnce(&Path) -> Result<(), String>>;

#[cfg(test)]
thread_local! {
    pub(super) static TEST_MARKER_INITIALIZATION_FAILURE: std::cell::RefCell<Option<MarkerInitializationHook>> = const { std::cell::RefCell::new(None) };
    pub(super) static TEST_PARTIAL_MARKER_WRITE_FAILURE: std::cell::Cell<bool> = const { std::cell::Cell::new(false) };
}

struct NewStagingDirectoryLease {
    path: PathBuf,
    #[cfg(windows)]
    handle: std::fs::File,
}

impl NewStagingDirectoryLease {
    fn open(path: &Path) -> Result<Self, String> {
        #[cfg(windows)]
        {
            use std::os::windows::fs::OpenOptionsExt;
            const DELETE: u32 = 0x0001_0000;
            const FILE_READ_ATTRIBUTES: u32 = 0x0000_0080;
            const FILE_SHARE_READ: u32 = 0x0000_0001;
            const FILE_SHARE_WRITE: u32 = 0x0000_0002;
            const FILE_FLAG_BACKUP_SEMANTICS: u32 = 0x0200_0000;
            const FILE_FLAG_OPEN_REPARSE_POINT: u32 = 0x0020_0000;

            let mut options = std::fs::OpenOptions::new();
            options
                .read(true)
                .access_mode(FILE_READ_ATTRIBUTES | DELETE)
                .share_mode(FILE_SHARE_READ | FILE_SHARE_WRITE)
                .custom_flags(FILE_FLAG_BACKUP_SEMANTICS | FILE_FLAG_OPEN_REPARSE_POINT);
            let handle = options
                .open(path)
                .map_err(|error| format!("Could not lease staging directory: {error}"))?;
            let metadata = handle
                .metadata()
                .map_err(|error| format!("Could not inspect leased staging directory: {error}"))?;
            if !metadata.is_dir() || is_reparse_metadata(&metadata) {
                return Err("The leased staging path was not a regular directory.".into());
            }
            Ok(Self {
                path: path.to_path_buf(),
                handle,
            })
        }
        #[cfg(not(windows))]
        {
            Ok(Self {
                path: path.to_path_buf(),
            })
        }
    }

    fn rollback(self, marker_file: Option<std::fs::File>) -> Result<(), String> {
        #[cfg(windows)]
        {
            let expected_entries = usize::from(marker_file.is_some());
            let entries = std::fs::read_dir(&self.path)
                .map_err(|error| format!("Could not inspect rollback entries: {error}"))?
                .collect::<Result<Vec<_>, _>>()
                .map_err(|error| format!("Could not inspect a rollback entry: {error}"))?;
            if entries.len() != expected_entries
                || entries.iter().any(|entry| {
                    marker_file.is_none()
                        || entry.file_name().as_os_str() != STAGING_MARKER_NAME
                        || entry
                            .file_type()
                            .map(|kind| !kind.is_file() || kind.is_symlink())
                            .unwrap_or(true)
                })
            {
                return Err("rollback found unexpected staging content".into());
            }

            if let Some(marker_file) = marker_file {
                let marker_path = self.path.join(STAGING_MARKER_NAME);
                verify_opened_marker_identity(&marker_file, &marker_path)?;
                mark_open_handle_for_deletion(&marker_file)?;
                drop(marker_file);
            }
            if std::fs::read_dir(&self.path)
                .map_err(|error| format!("Could not re-inspect rollback directory: {error}"))?
                .next()
                .is_some()
            {
                return Err("rollback directory was no longer empty".into());
            }
            mark_open_handle_for_deletion(&self.handle)?;
            drop(self);
            Ok(())
        }
        #[cfg(not(windows))]
        {
            let _ = marker_file;
            Err("safe handle-bound rollback is unavailable on this platform".into())
        }
    }
}

fn staging_root(output_dir: &Path) -> PathBuf {
    output_dir.join(STAGING_ROOT_NAME)
}

pub(in crate::downloader) fn build_staging_dir(output_dir: &Path, download_id: &str) -> PathBuf {
    // Operation IDs are generated by the backend, but retain a strict UUID
    // fallback for legacy renderer-generated IDs during the 0.6.0 bridge.
    let safe_id = uuid::Uuid::parse_str(download_id.trim())
        .map(|id| id.to_string())
        .unwrap_or_else(|_| uuid::Uuid::new_v4().to_string());
    staging_root(output_dir).join(safe_id)
}

pub(in crate::downloader) fn reset_staging_dir(
    path: &Path,
    output_dir: &Path,
    operation_id: &str,
) -> Result<(), String> {
    let (root, operation_path, normalized_id) =
        validate_staging_layout(path, output_dir, operation_id, false)?;
    if operation_path.exists() {
        quarantine_and_remove_staging_dir(&root, &operation_path, &normalized_id, true)
            .map_err(|error| format!("Failed to reset staging folder: {error}"))?;
    }

    mark_hidden(&root)?;
    std::fs::create_dir(&operation_path)
        .map_err(|error| format!("Failed to create staging folder: {error}"))?;
    // Windows does not expose an atomic std create-directory-and-open-handle
    // operation. A same-user actor monitoring this private staging parent
    // could replace the UUID directory in that short gap; that actor is
    // outside the supported filesystem trust boundary. The retained handle
    // fixes identity from this point on.
    let directory_lease = match NewStagingDirectoryLease::open(&operation_path) {
        Ok(lease) => lease,
        Err(error) => {
            return Err(format!(
                "Failed to secure the newly-created staging folder: {error} The folder was preserved."
            ));
        }
    };
    let mut marker_file = None;
    let marker_initialization = (|| {
        #[cfg(test)]
        TEST_MARKER_INITIALIZATION_FAILURE.with(|hook| {
            if let Some(hook) = hook.borrow_mut().take() {
                hook(&operation_path)?;
            }
            Ok::<(), String>(())
        })?;
        let marker = serde_json::json!({
            "schemaVersion": 1,
            "owner": "nuclear-downloader",
            "operationId": normalized_id,
        });
        let marker_bytes = serde_json::to_vec(&marker).map_err(|error| error.to_string())?;
        marker_file = Some(open_new_staging_marker(
            &operation_path.join(STAGING_MARKER_NAME),
        )?);
        #[cfg(test)]
        if TEST_PARTIAL_MARKER_WRITE_FAILURE.with(|failure| failure.replace(false)) {
            marker_file
                .as_mut()
                .expect("marker handle was just stored")
                .write_all(b"{")
                .map_err(|error| format!("Failed to inject a partial marker write: {error}"))?;
            return Err("forced partial marker write failure".to_string());
        }
        let marker_file = marker_file
            .as_mut()
            .expect("marker handle was stored before initialization");
        marker_file
            .write_all(&marker_bytes)
            .and_then(|()| marker_file.sync_all())
            .map_err(|error| format!("Failed to write staging ownership marker: {error}"))?;
        verify_opened_staging_marker(marker_file, &operation_path, &normalized_id, true)
    })();
    if let Err(error) = marker_initialization {
        return match directory_lease.rollback(marker_file) {
            Ok(()) => Err(error),
            Err(rollback_error) => Err(format!(
                "{error} The incomplete staging folder was preserved ({rollback_error})."
            )),
        };
    }
    drop(marker_file);
    drop(directory_lease);
    Ok(())
}

fn open_new_staging_marker(path: &Path) -> Result<std::fs::File, String> {
    let mut options = std::fs::OpenOptions::new();
    options.read(true).write(true).create_new(true);
    #[cfg(windows)]
    {
        use std::os::windows::fs::OpenOptionsExt;
        const DELETE: u32 = 0x0001_0000;
        const GENERIC_READ: u32 = 0x8000_0000;
        const GENERIC_WRITE: u32 = 0x4000_0000;
        const FILE_SHARE_READ: u32 = 0x0000_0001;
        const FILE_FLAG_OPEN_REPARSE_POINT: u32 = 0x0020_0000;
        options
            .access_mode(GENERIC_READ | GENERIC_WRITE | DELETE)
            .share_mode(FILE_SHARE_READ)
            .custom_flags(FILE_FLAG_OPEN_REPARSE_POINT);
    }
    options
        .open(path)
        .map_err(|error| format!("Failed to create staging ownership marker: {error}"))
}

#[cfg(windows)]
fn mark_open_handle_for_deletion(file: &std::fs::File) -> Result<(), String> {
    crate::windows_file::mark_for_deletion(file)
        .map_err(|error| format!("Could not mark an owned staging handle for deletion: {error}"))
}

pub(super) fn cleanup_staging_dir(
    path: &Path,
    output_dir: &Path,
    operation_id: &str,
) -> Result<(), String> {
    let (root, operation_path, normalized_id) =
        validate_staging_layout(path, output_dir, operation_id, true)?;
    quarantine_and_remove_staging_dir(&root, &operation_path, &normalized_id, true)
        .map_err(|error| format!("Failed to clean staging folder: {error}"))
}

pub(in crate::downloader) fn cleanup_staging_with_warning(
    notifications: &DownloadNotifications,
    path: &Path,
    output_dir: &Path,
    operation_id: &str,
) {
    if let Err(error) = cleanup_staging_dir(path, output_dir, operation_id) {
        (notifications.cleanup_warning)(operation_id, &error);
    }
}

fn quarantine_and_remove_staging_dir(
    root: &Path,
    source: &Path,
    operation_id: &str,
    require_operation_name: bool,
) -> Result<(), String> {
    validate_owned_staging_directory(root, source, operation_id, require_operation_name)?;
    let quarantine = root.join(format!(
        "{STAGING_CLEANUP_PREFIX}{operation_id}.{}",
        uuid::Uuid::new_v4()
    ));
    if quarantine.exists() {
        return Err("A staging quarantine destination unexpectedly already exists.".into());
    }
    std::fs::rename(source, &quarantine)
        .map_err(|error| format!("Could not atomically quarantine staging data: {error}"))?;
    validate_owned_staging_directory(root, &quarantine, operation_id, false)?;
    // Rust's recursive removal does not traverse directory symlinks. Combined
    // with the same-volume quarantine rename and the second identity check,
    // a replaced source path can never redirect deletion outside this root.
    std::fs::remove_dir_all(&quarantine)
        .map_err(|error| format!("Could not remove quarantined staging data: {error}"))
}

fn validate_owned_staging_directory(
    root: &Path,
    path: &Path,
    operation_id: &str,
    require_operation_name: bool,
) -> Result<(), String> {
    let root_metadata = std::fs::symlink_metadata(root)
        .map_err(|error| format!("Failed to inspect staging root: {error}"))?;
    let metadata = std::fs::symlink_metadata(path)
        .map_err(|error| format!("Failed to inspect staging operation: {error}"))?;
    if !root_metadata.is_dir()
        || is_reparse_metadata(&root_metadata)
        || !metadata.is_dir()
        || is_reparse_metadata(&metadata)
    {
        return Err("Staging cleanup requires regular non-reparse directories.".into());
    }
    let canonical_root = root
        .canonicalize()
        .map_err(|error| format!("Failed to resolve staging root: {error}"))?;
    let canonical_path = path
        .canonicalize()
        .map_err(|error| format!("Failed to resolve staging operation: {error}"))?;
    if canonical_path.parent() != Some(canonical_root.as_path()) {
        return Err("Staging cleanup target escaped its staging root.".into());
    }
    verify_staging_marker_with_name_policy(path, operation_id, require_operation_name)
}

fn validate_staging_layout(
    path: &Path,
    output_dir: &Path,
    operation_id: &str,
    require_operation: bool,
) -> Result<(PathBuf, PathBuf, String), String> {
    let normalized_id = uuid::Uuid::parse_str(operation_id.trim())
        .map_err(|_| "Staging operation ID was not a UUID.".to_string())?
        .to_string();
    let expected_lexical = staging_root(output_dir).join(&normalized_id);
    if path != expected_lexical {
        return Err("Refusing to use a staging folder outside the expected operation path.".into());
    }
    let output_metadata = std::fs::symlink_metadata(output_dir)
        .map_err(|error| format!("Failed to inspect output folder: {error}"))?;
    if !output_metadata.is_dir() || is_reparse_metadata(&output_metadata) {
        return Err("Output folder was not a regular non-reparse directory.".into());
    }
    let canonical_output = output_dir
        .canonicalize()
        .map_err(|error| format!("Failed to resolve output folder: {error}"))?;
    let root = staging_root(&canonical_output);
    match std::fs::symlink_metadata(&root) {
        Ok(metadata) => {
            if !metadata.is_dir() || is_reparse_metadata(&metadata) {
                return Err("Staging root was not a regular non-reparse directory.".into());
            }
            let canonical_root = root
                .canonicalize()
                .map_err(|error| format!("Failed to resolve staging root: {error}"))?;
            if canonical_root.parent() != Some(canonical_output.as_path()) {
                return Err("Staging root escaped the output folder.".into());
            }
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound && !require_operation => {
            std::fs::create_dir(&root)
                .map_err(|error| format!("Failed to create staging root: {error}"))?;
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            return Err("Staging root did not exist.".into());
        }
        Err(error) => return Err(format!("Failed to inspect staging root: {error}")),
    }
    let operation_path = root.join(&normalized_id);
    match std::fs::symlink_metadata(&operation_path) {
        Ok(metadata) => {
            if !metadata.is_dir() || is_reparse_metadata(&metadata) {
                return Err("Staging operation was not a regular non-reparse directory.".into());
            }
            let canonical_operation = operation_path
                .canonicalize()
                .map_err(|error| format!("Failed to resolve staging operation: {error}"))?;
            if canonical_operation.parent() != Some(root.as_path()) {
                return Err("Staging operation escaped the staging root.".into());
            }
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound && !require_operation => {}
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            return Err("Staging operation did not exist.".into());
        }
        Err(error) => return Err(format!("Failed to inspect staging operation: {error}")),
    }
    Ok((root, operation_path, normalized_id))
}

#[cfg(test)]
pub(super) fn verify_staging_marker(
    path: &Path,
    expected_operation_id: &str,
) -> Result<(), String> {
    verify_staging_marker_with_name_policy(path, expected_operation_id, true)
}

fn verify_staging_marker_with_name_policy(
    path: &Path,
    expected_operation_id: &str,
    require_operation_name: bool,
) -> Result<(), String> {
    let marker_path = path.join(STAGING_MARKER_NAME);
    let mut marker_file = open_staging_marker(&marker_path)?;
    verify_opened_staging_marker(
        &mut marker_file,
        path,
        expected_operation_id,
        require_operation_name,
    )
}

fn verify_opened_staging_marker(
    marker_file: &mut std::fs::File,
    directory: &Path,
    expected_operation_id: &str,
    require_operation_name: bool,
) -> Result<(), String> {
    let marker_path = directory.join(STAGING_MARKER_NAME);
    let marker_metadata = marker_file
        .metadata()
        .map_err(|_| "Staging ownership marker could not be inspected.".to_string())?;
    if marker_metadata.len() > MAX_STAGING_MARKER_BYTES {
        return Err("Staging ownership marker exceeded the 4 KiB limit.".into());
    }
    let mut marker_bytes = Vec::with_capacity(marker_metadata.len() as usize);
    marker_file
        .seek(std::io::SeekFrom::Start(0))
        .map_err(|_| "Staging ownership marker could not be read.".to_string())?;
    (&mut *marker_file)
        .take(MAX_STAGING_MARKER_BYTES + 1)
        .read_to_end(&mut marker_bytes)
        .map_err(|_| "Staging ownership marker could not be read.".to_string())?;
    if marker_bytes.len() as u64 > MAX_STAGING_MARKER_BYTES {
        return Err("Staging ownership marker exceeded the 4 KiB limit.".into());
    }
    verify_opened_marker_identity(marker_file, &marker_path)?;
    let marker: serde_json::Value = serde_json::from_slice(&marker_bytes)
        .map_err(|_| "Staging ownership marker was invalid.".to_string())?;
    let directory_id = directory.file_name().and_then(|name| name.to_str());
    if marker["schemaVersion"] != 1
        || marker["owner"] != "nuclear-downloader"
        || marker["operationId"] != expected_operation_id
        || (require_operation_name && directory_id != Some(expected_operation_id))
    {
        return Err("Staging ownership marker was not recognized.".to_string());
    }
    Ok(())
}

fn open_staging_marker(path: &Path) -> Result<std::fs::File, String> {
    let path_metadata = std::fs::symlink_metadata(path)
        .map_err(|_| "Staging folder did not contain an ownership marker.".to_string())?;
    if !path_metadata.is_file() || is_reparse_metadata(&path_metadata) {
        return Err("Staging ownership marker was not a regular non-reparse file.".into());
    }

    let mut options = std::fs::OpenOptions::new();
    options.read(true);
    #[cfg(windows)]
    {
        use std::os::windows::fs::OpenOptionsExt;
        const FILE_SHARE_READ: u32 = 0x0000_0001;
        const FILE_FLAG_OPEN_REPARSE_POINT: u32 = 0x0020_0000;
        options
            .share_mode(FILE_SHARE_READ)
            .custom_flags(FILE_FLAG_OPEN_REPARSE_POINT);
    }
    let file = options
        .open(path)
        .map_err(|_| "Staging folder did not contain an ownership marker.".to_string())?;
    let opened_metadata = file
        .metadata()
        .map_err(|_| "Staging ownership marker could not be inspected.".to_string())?;
    if !opened_metadata.is_file() || is_reparse_metadata(&opened_metadata) {
        return Err("Staging ownership marker was not a regular non-reparse file.".into());
    }
    verify_opened_marker_identity(&file, path)?;
    Ok(file)
}

#[cfg(windows)]
fn verify_opened_marker_identity(opened: &std::fs::File, path: &Path) -> Result<(), String> {
    use std::os::windows::fs::OpenOptionsExt;

    const FILE_SHARE_READ: u32 = 0x0000_0001;
    const FILE_SHARE_WRITE: u32 = 0x0000_0002;
    const FILE_SHARE_DELETE: u32 = 0x0000_0004;
    const FILE_FLAG_OPEN_REPARSE_POINT: u32 = 0x0020_0000;

    fn identity(file: &std::fs::File) -> Result<crate::windows_file::FileIdentity, String> {
        crate::windows_file::identity(file)
            .map_err(|_| "Staging ownership marker identity could not be verified.".to_string())
    }

    let current_metadata = std::fs::symlink_metadata(path)
        .map_err(|_| "Staging ownership marker path changed while it was open.".to_string())?;
    if !current_metadata.is_file() || is_reparse_metadata(&current_metadata) {
        return Err("Staging ownership marker path changed while it was open.".into());
    }
    let mut options = std::fs::OpenOptions::new();
    // This short-lived comparison handle shares all access so it can coexist
    // with the retained writer/delete handle. The retained handle's narrower
    // share mode still prevents external mutation or replacement.
    options
        .read(true)
        .share_mode(FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE)
        .custom_flags(FILE_FLAG_OPEN_REPARSE_POINT);
    let current = options
        .open(path)
        .map_err(|_| "Staging ownership marker path changed while it was open.".to_string())?;
    let current_metadata = current
        .metadata()
        .map_err(|_| "Staging ownership marker path changed while it was open.".to_string())?;
    if !current_metadata.is_file()
        || is_reparse_metadata(&current_metadata)
        || identity(opened)? != identity(&current)?
    {
        return Err("Staging ownership marker path changed while it was open.".into());
    }
    Ok(())
}

#[cfg(unix)]
fn verify_opened_marker_identity(opened: &std::fs::File, path: &Path) -> Result<(), String> {
    use std::os::unix::fs::MetadataExt;

    let current_path_metadata = std::fs::symlink_metadata(path)
        .map_err(|_| "Staging ownership marker path changed while it was open.".to_string())?;
    if !current_path_metadata.is_file() || is_reparse_metadata(&current_path_metadata) {
        return Err("Staging ownership marker path changed while it was open.".into());
    }
    let opened_metadata = opened
        .metadata()
        .map_err(|_| "Staging ownership marker identity could not be verified.".to_string())?;
    let current_metadata = std::fs::metadata(path)
        .map_err(|_| "Staging ownership marker path changed while it was open.".to_string())?;
    if opened_metadata.dev() != current_metadata.dev()
        || opened_metadata.ino() != current_metadata.ino()
    {
        return Err("Staging ownership marker path changed while it was open.".into());
    }
    Ok(())
}

#[cfg(not(any(windows, unix)))]
fn verify_opened_marker_identity(_opened: &std::fs::File, path: &Path) -> Result<(), String> {
    let current_metadata = std::fs::symlink_metadata(path)
        .map_err(|_| "Staging ownership marker path changed while it was open.".to_string())?;
    if !current_metadata.is_file() || is_reparse_metadata(&current_metadata) {
        return Err("Staging ownership marker path changed while it was open.".into());
    }
    Ok(())
}

pub(crate) fn cleanup_abandoned_download_stages(output_roots: &[String]) -> Vec<String> {
    let mut failures = Vec::new();
    for (root_index, output_root) in output_roots.iter().enumerate() {
        if let Err(error) = cleanup_abandoned_download_stages_at(Path::new(output_root)) {
            failures.push(format!("Output root {root_index}: {error}"));
        }
    }
    failures
}

pub(super) fn cleanup_abandoned_download_stages_at(output_root: &Path) -> Result<(), String> {
    let output_metadata = match std::fs::symlink_metadata(output_root) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(error) => return Err(format!("could not inspect output root ({})", error.kind())),
    };
    if !output_metadata.is_dir() || is_reparse_metadata(&output_metadata) {
        return Err("output root is not a regular non-reparse directory".to_string());
    }
    let output_root = output_root
        .canonicalize()
        .map_err(|error| format!("could not resolve output root ({})", error.kind()))?;
    let staging_root = staging_root(&output_root);
    let staging_metadata = match std::fs::symlink_metadata(&staging_root) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(error) => return Err(format!("could not inspect staging root ({})", error.kind())),
    };
    if !staging_metadata.is_dir() || is_reparse_metadata(&staging_metadata) {
        return Err("staging root is not a regular non-reparse directory".to_string());
    }

    let entries = std::fs::read_dir(&staging_root)
        .map_err(|error| format!("could not enumerate staging root ({})", error.kind()))?;
    for entry in entries {
        let entry =
            entry.map_err(|error| format!("could not inspect staging entry ({})", error.kind()))?;
        let path = entry.path();
        let name = entry.file_name();
        let Some(name) = name.to_str() else {
            continue;
        };
        let operation_id = if uuid::Uuid::parse_str(name).is_ok() {
            name.to_string()
        } else if let Some(rest) = name.strip_prefix(STAGING_CLEANUP_PREFIX) {
            let Some((operation_id, quarantine_id)) = rest.split_once('.') else {
                continue;
            };
            if uuid::Uuid::parse_str(operation_id).is_err()
                || uuid::Uuid::parse_str(quarantine_id).is_err()
            {
                continue;
            }
            operation_id.to_string()
        } else {
            continue;
        };
        let metadata = std::fs::symlink_metadata(&path)
            .map_err(|error| format!("could not inspect staging operation ({})", error.kind()))?;
        if !metadata.is_dir() || is_reparse_metadata(&metadata) {
            continue;
        }
        if verify_staging_marker_with_name_policy(
            &path,
            &operation_id,
            uuid::Uuid::parse_str(name).is_ok(),
        )
        .is_err()
        {
            continue;
        }
        quarantine_and_remove_staging_dir(&staging_root, &path, &operation_id, false)?;
    }
    Ok(())
}

pub(super) fn is_reparse_metadata(metadata: &std::fs::Metadata) -> bool {
    if metadata.file_type().is_symlink() {
        return true;
    }
    #[cfg(windows)]
    {
        use std::os::windows::fs::MetadataExt;
        const FILE_ATTRIBUTE_REPARSE_POINT: u32 = 0x400;
        metadata.file_attributes() & FILE_ATTRIBUTE_REPARSE_POINT != 0
    }
    #[cfg(not(windows))]
    false
}

#[cfg(windows)]
fn mark_hidden(path: &Path) -> Result<(), String> {
    use std::os::windows::ffi::OsStrExt;
    const FILE_ATTRIBUTE_HIDDEN: u32 = 0x2;
    #[link(name = "Kernel32")]
    extern "system" {
        fn GetFileAttributesW(path: *const u16) -> u32;
        fn SetFileAttributesW(path: *const u16, attributes: u32) -> i32;
    }
    let wide = path
        .as_os_str()
        .encode_wide()
        .chain(Some(0))
        .collect::<Vec<_>>();
    let attributes = unsafe { GetFileAttributesW(wide.as_ptr()) };
    if attributes == u32::MAX
        || unsafe { SetFileAttributesW(wide.as_ptr(), attributes | FILE_ATTRIBUTE_HIDDEN) } == 0
    {
        return Err(format!(
            "Failed to hide staging root: {}",
            std::io::Error::last_os_error()
        ));
    }
    Ok(())
}

#[cfg(not(windows))]
fn mark_hidden(_path: &Path) -> Result<(), String> {
    Ok(())
}
