use super::process::DownloadJob;
use super::{normalize_filename_override, sanitize_filename_component, MAX_ACTIONABLE_FIELD_BYTES};
use crate::models::DownloadRequest;
use serde::Deserialize;
use std::io::{Read, Seek, Write};
use std::path::{Path, PathBuf};
use tauri::AppHandle;

const MAX_OUTPUT_SUFFIX: usize = 9_999;
const STAGING_ROOT_NAME: &str = ".nuclear-downloader-staging";
const STAGING_MARKER_NAME: &str = ".nuclear-downloader-owner-v1.json";
const STAGING_CLEANUP_PREFIX: &str = ".cleanup-";
const FINAL_OUTPUT_RECORD_NAME: &str = ".nuclear-final-output-v1.jsonl";
const MAX_FINAL_OUTPUT_RECORD_BYTES: u64 = 64 * 1024;
const MAX_STAGING_MARKER_BYTES: u64 = 4 * 1024;

#[cfg(test)]
type MarkerInitializationHook = Box<dyn FnOnce(&Path) -> Result<(), String>>;

#[cfg(test)]
thread_local! {
    static TEST_MARKER_INITIALIZATION_FAILURE: std::cell::RefCell<Option<MarkerInitializationHook>> = const { std::cell::RefCell::new(None) };
    static TEST_PARTIAL_MARKER_WRITE_FAILURE: std::cell::Cell<bool> = const {
        std::cell::Cell::new(false)
    };
    static TEST_FINAL_OUTPUT_RECORD_READ_BYTES: std::cell::Cell<usize> = const {
        std::cell::Cell::new(0)
    };
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct FinalOutputRecord {
    schema_version: u8,
    filepath: String,
}

#[derive(Debug)]
pub(super) struct StagedOutputError {
    pub(super) code: &'static str,
    pub(super) message: String,
}

fn final_output_record_path(staging_dir: &Path) -> PathBuf {
    staging_dir.join(FINAL_OUTPUT_RECORD_NAME)
}

pub(super) fn append_final_output_record_args(args: &mut Vec<String>, staging_dir: &Path) {
    let record_path = final_output_record_path(staging_dir)
        .to_string_lossy()
        .replace('\\', "/")
        .replace('%', "%%");
    args.push("--print-to-file".to_string());
    args.push(r#"after_move:{"schema_version":1,"filepath":%(filepath)j}"#.to_string());
    args.push(record_path);
}

fn staging_root(output_dir: &Path) -> PathBuf {
    output_dir.join(STAGING_ROOT_NAME)
}

pub(super) fn build_staging_dir(output_dir: &Path, download_id: &str) -> PathBuf {
    // Operation IDs are generated by the backend, but retain a strict UUID
    // fallback for legacy renderer-generated IDs during the 0.6.0 bridge.
    let safe_id = uuid::Uuid::parse_str(download_id.trim())
        .map(|id| id.to_string())
        .unwrap_or_else(|_| uuid::Uuid::new_v4().to_string());
    staging_root(output_dir).join(safe_id)
}

pub(super) fn reset_staging_dir(
    path: &Path,
    output_dir: &Path,
    operation_id: &str,
) -> Result<(), String> {
    let (root, operation_path, normalized_id) =
        validate_staging_layout(path, output_dir, operation_id, false)?;
    if operation_path.exists() {
        quarantine_and_remove_staging_dir(&root, &operation_path, &normalized_id, true)
            .map_err(|error| format!("Failed to reset staging folder: {error}"))?;
    }

    mark_hidden(&root)?;
    std::fs::create_dir(&operation_path)
        .map_err(|error| format!("Failed to create staging folder: {error}"))?;
    // Windows does not expose an atomic std create-directory-and-open-handle
    // operation. A same-user actor monitoring this private staging parent
    // could replace the UUID directory in that short gap; that actor is
    // outside the supported filesystem trust boundary. The retained handle
    // fixes identity from this point on.
    let directory_lease = match NewStagingDirectoryLease::open(&operation_path) {
        Ok(lease) => lease,
        Err(error) => {
            return Err(format!(
                "Failed to secure the newly-created staging folder: {error} The folder was preserved."
            ));
        }
    };
    let mut marker_file = None;
    let marker_initialization = (|| {
        #[cfg(test)]
        TEST_MARKER_INITIALIZATION_FAILURE.with(|hook| {
            if let Some(hook) = hook.borrow_mut().take() {
                hook(&operation_path)?;
            }
            Ok::<(), String>(())
        })?;
        let marker = serde_json::json!({
            "schemaVersion": 1,
            "owner": "nuclear-downloader",
            "operationId": normalized_id,
        });
        let marker_bytes = serde_json::to_vec(&marker).map_err(|error| error.to_string())?;
        marker_file = Some(open_new_staging_marker(
            &operation_path.join(STAGING_MARKER_NAME),
        )?);
        #[cfg(test)]
        if TEST_PARTIAL_MARKER_WRITE_FAILURE.with(|failure| failure.replace(false)) {
            marker_file
                .as_mut()
                .expect("marker handle was just stored")
                .write_all(b"{")
                .map_err(|error| format!("Failed to inject a partial marker write: {error}"))?;
            return Err("forced partial marker write failure".to_string());
        }
        let marker_file = marker_file
            .as_mut()
            .expect("marker handle was stored before initialization");
        marker_file
            .write_all(&marker_bytes)
            .and_then(|()| marker_file.sync_all())
            .map_err(|error| format!("Failed to write staging ownership marker: {error}"))?;
        verify_opened_staging_marker(marker_file, &operation_path, &normalized_id, true)
    })();
    if let Err(error) = marker_initialization {
        return match directory_lease.rollback(marker_file) {
            Ok(()) => Err(error),
            Err(rollback_error) => Err(format!(
                "{error} The incomplete staging folder was preserved ({rollback_error})."
            )),
        };
    }
    drop(marker_file);
    drop(directory_lease);
    Ok(())
}

fn open_new_staging_marker(path: &Path) -> Result<std::fs::File, String> {
    let mut options = std::fs::OpenOptions::new();
    options.read(true).write(true).create_new(true);
    #[cfg(windows)]
    {
        use std::os::windows::fs::OpenOptionsExt;
        const DELETE: u32 = 0x0001_0000;
        const GENERIC_READ: u32 = 0x8000_0000;
        const GENERIC_WRITE: u32 = 0x4000_0000;
        const FILE_SHARE_READ: u32 = 0x0000_0001;
        const FILE_FLAG_OPEN_REPARSE_POINT: u32 = 0x0020_0000;
        options
            .access_mode(GENERIC_READ | GENERIC_WRITE | DELETE)
            .share_mode(FILE_SHARE_READ)
            .custom_flags(FILE_FLAG_OPEN_REPARSE_POINT);
    }
    options
        .open(path)
        .map_err(|error| format!("Failed to create staging ownership marker: {error}"))
}

struct NewStagingDirectoryLease {
    path: PathBuf,
    #[cfg(windows)]
    handle: std::fs::File,
}

impl NewStagingDirectoryLease {
    fn open(path: &Path) -> Result<Self, String> {
        #[cfg(windows)]
        {
            use std::os::windows::fs::OpenOptionsExt;
            const DELETE: u32 = 0x0001_0000;
            const FILE_READ_ATTRIBUTES: u32 = 0x0000_0080;
            const FILE_SHARE_READ: u32 = 0x0000_0001;
            const FILE_SHARE_WRITE: u32 = 0x0000_0002;
            const FILE_FLAG_BACKUP_SEMANTICS: u32 = 0x0200_0000;
            const FILE_FLAG_OPEN_REPARSE_POINT: u32 = 0x0020_0000;

            let mut options = std::fs::OpenOptions::new();
            options
                .read(true)
                .access_mode(FILE_READ_ATTRIBUTES | DELETE)
                .share_mode(FILE_SHARE_READ | FILE_SHARE_WRITE)
                .custom_flags(FILE_FLAG_BACKUP_SEMANTICS | FILE_FLAG_OPEN_REPARSE_POINT);
            let handle = options
                .open(path)
                .map_err(|error| format!("Could not lease staging directory: {error}"))?;
            let metadata = handle
                .metadata()
                .map_err(|error| format!("Could not inspect leased staging directory: {error}"))?;
            if !metadata.is_dir() || is_reparse_metadata(&metadata) {
                return Err("The leased staging path was not a regular directory.".into());
            }
            Ok(Self {
                path: path.to_path_buf(),
                handle,
            })
        }
        #[cfg(not(windows))]
        {
            Ok(Self {
                path: path.to_path_buf(),
            })
        }
    }

    fn rollback(self, marker_file: Option<std::fs::File>) -> Result<(), String> {
        #[cfg(windows)]
        {
            let expected_entries = usize::from(marker_file.is_some());
            let entries = std::fs::read_dir(&self.path)
                .map_err(|error| format!("Could not inspect rollback entries: {error}"))?
                .collect::<Result<Vec<_>, _>>()
                .map_err(|error| format!("Could not inspect a rollback entry: {error}"))?;
            if entries.len() != expected_entries
                || entries.iter().any(|entry| {
                    marker_file.is_none()
                        || entry.file_name().as_os_str() != STAGING_MARKER_NAME
                        || entry
                            .file_type()
                            .map(|kind| !kind.is_file() || kind.is_symlink())
                            .unwrap_or(true)
                })
            {
                return Err("rollback found unexpected staging content".into());
            }

            if let Some(marker_file) = marker_file {
                let marker_path = self.path.join(STAGING_MARKER_NAME);
                verify_opened_marker_identity(&marker_file, &marker_path)?;
                mark_open_handle_for_deletion(&marker_file)?;
                drop(marker_file);
            }
            if std::fs::read_dir(&self.path)
                .map_err(|error| format!("Could not re-inspect rollback directory: {error}"))?
                .next()
                .is_some()
            {
                return Err("rollback directory was no longer empty".into());
            }
            mark_open_handle_for_deletion(&self.handle)?;
            drop(self);
            Ok(())
        }
        #[cfg(not(windows))]
        {
            let _ = marker_file;
            Err("safe handle-bound rollback is unavailable on this platform".into())
        }
    }
}

#[cfg(windows)]
fn mark_open_handle_for_deletion(file: &std::fs::File) -> Result<(), String> {
    crate::windows_file::mark_for_deletion(file)
        .map_err(|error| format!("Could not mark an owned staging handle for deletion: {error}"))
}

fn cleanup_staging_dir(path: &Path, output_dir: &Path, operation_id: &str) -> Result<(), String> {
    let (root, operation_path, normalized_id) =
        validate_staging_layout(path, output_dir, operation_id, true)?;
    quarantine_and_remove_staging_dir(&root, &operation_path, &normalized_id, true)
        .map_err(|error| format!("Failed to clean staging folder: {error}"))
}

pub(super) fn cleanup_staging_with_warning(
    app: &AppHandle,
    path: &Path,
    output_dir: &Path,
    operation_id: &str,
) {
    if let Err(error) = cleanup_staging_dir(path, output_dir, operation_id) {
        crate::record_download_cleanup_warning(app, operation_id, &error);
    }
}

fn quarantine_and_remove_staging_dir(
    root: &Path,
    source: &Path,
    operation_id: &str,
    require_operation_name: bool,
) -> Result<(), String> {
    validate_owned_staging_directory(root, source, operation_id, require_operation_name)?;
    let quarantine = root.join(format!(
        "{STAGING_CLEANUP_PREFIX}{operation_id}.{}",
        uuid::Uuid::new_v4()
    ));
    if quarantine.exists() {
        return Err("A staging quarantine destination unexpectedly already exists.".into());
    }
    std::fs::rename(source, &quarantine)
        .map_err(|error| format!("Could not atomically quarantine staging data: {error}"))?;
    validate_owned_staging_directory(root, &quarantine, operation_id, false)?;
    // Rust's recursive removal does not traverse directory symlinks. Combined
    // with the same-volume quarantine rename and the second identity check,
    // a replaced source path can never redirect deletion outside this root.
    std::fs::remove_dir_all(&quarantine)
        .map_err(|error| format!("Could not remove quarantined staging data: {error}"))
}

fn validate_owned_staging_directory(
    root: &Path,
    path: &Path,
    operation_id: &str,
    require_operation_name: bool,
) -> Result<(), String> {
    let root_metadata = std::fs::symlink_metadata(root)
        .map_err(|error| format!("Failed to inspect staging root: {error}"))?;
    let metadata = std::fs::symlink_metadata(path)
        .map_err(|error| format!("Failed to inspect staging operation: {error}"))?;
    if !root_metadata.is_dir()
        || is_reparse_metadata(&root_metadata)
        || !metadata.is_dir()
        || is_reparse_metadata(&metadata)
    {
        return Err("Staging cleanup requires regular non-reparse directories.".into());
    }
    let canonical_root = root
        .canonicalize()
        .map_err(|error| format!("Failed to resolve staging root: {error}"))?;
    let canonical_path = path
        .canonicalize()
        .map_err(|error| format!("Failed to resolve staging operation: {error}"))?;
    if canonical_path.parent() != Some(canonical_root.as_path()) {
        return Err("Staging cleanup target escaped its staging root.".into());
    }
    verify_staging_marker_with_name_policy(path, operation_id, require_operation_name)
}

fn validate_staging_layout(
    path: &Path,
    output_dir: &Path,
    operation_id: &str,
    require_operation: bool,
) -> Result<(PathBuf, PathBuf, String), String> {
    let normalized_id = uuid::Uuid::parse_str(operation_id.trim())
        .map_err(|_| "Staging operation ID was not a UUID.".to_string())?
        .to_string();
    let expected_lexical = staging_root(output_dir).join(&normalized_id);
    if path != expected_lexical {
        return Err("Refusing to use a staging folder outside the expected operation path.".into());
    }
    let output_metadata = std::fs::symlink_metadata(output_dir)
        .map_err(|error| format!("Failed to inspect output folder: {error}"))?;
    if !output_metadata.is_dir() || is_reparse_metadata(&output_metadata) {
        return Err("Output folder was not a regular non-reparse directory.".into());
    }
    let canonical_output = output_dir
        .canonicalize()
        .map_err(|error| format!("Failed to resolve output folder: {error}"))?;
    let root = staging_root(&canonical_output);
    match std::fs::symlink_metadata(&root) {
        Ok(metadata) => {
            if !metadata.is_dir() || is_reparse_metadata(&metadata) {
                return Err("Staging root was not a regular non-reparse directory.".into());
            }
            let canonical_root = root
                .canonicalize()
                .map_err(|error| format!("Failed to resolve staging root: {error}"))?;
            if canonical_root.parent() != Some(canonical_output.as_path()) {
                return Err("Staging root escaped the output folder.".into());
            }
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound && !require_operation => {
            std::fs::create_dir(&root)
                .map_err(|error| format!("Failed to create staging root: {error}"))?;
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            return Err("Staging root did not exist.".into());
        }
        Err(error) => return Err(format!("Failed to inspect staging root: {error}")),
    }
    let operation_path = root.join(&normalized_id);
    match std::fs::symlink_metadata(&operation_path) {
        Ok(metadata) => {
            if !metadata.is_dir() || is_reparse_metadata(&metadata) {
                return Err("Staging operation was not a regular non-reparse directory.".into());
            }
            let canonical_operation = operation_path
                .canonicalize()
                .map_err(|error| format!("Failed to resolve staging operation: {error}"))?;
            if canonical_operation.parent() != Some(root.as_path()) {
                return Err("Staging operation escaped the staging root.".into());
            }
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound && !require_operation => {}
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            return Err("Staging operation did not exist.".into());
        }
        Err(error) => return Err(format!("Failed to inspect staging operation: {error}")),
    }
    Ok((root, operation_path, normalized_id))
}

#[cfg(test)]
fn verify_staging_marker(path: &Path, expected_operation_id: &str) -> Result<(), String> {
    verify_staging_marker_with_name_policy(path, expected_operation_id, true)
}

fn verify_staging_marker_with_name_policy(
    path: &Path,
    expected_operation_id: &str,
    require_operation_name: bool,
) -> Result<(), String> {
    let marker_path = path.join(STAGING_MARKER_NAME);
    let mut marker_file = open_staging_marker(&marker_path)?;
    verify_opened_staging_marker(
        &mut marker_file,
        path,
        expected_operation_id,
        require_operation_name,
    )
}

fn verify_opened_staging_marker(
    marker_file: &mut std::fs::File,
    directory: &Path,
    expected_operation_id: &str,
    require_operation_name: bool,
) -> Result<(), String> {
    let marker_path = directory.join(STAGING_MARKER_NAME);
    let marker_metadata = marker_file
        .metadata()
        .map_err(|_| "Staging ownership marker could not be inspected.".to_string())?;
    if marker_metadata.len() > MAX_STAGING_MARKER_BYTES {
        return Err("Staging ownership marker exceeded the 4 KiB limit.".into());
    }
    let mut marker_bytes = Vec::with_capacity(marker_metadata.len() as usize);
    marker_file
        .seek(std::io::SeekFrom::Start(0))
        .map_err(|_| "Staging ownership marker could not be read.".to_string())?;
    (&mut *marker_file)
        .take(MAX_STAGING_MARKER_BYTES + 1)
        .read_to_end(&mut marker_bytes)
        .map_err(|_| "Staging ownership marker could not be read.".to_string())?;
    if marker_bytes.len() as u64 > MAX_STAGING_MARKER_BYTES {
        return Err("Staging ownership marker exceeded the 4 KiB limit.".into());
    }
    verify_opened_marker_identity(marker_file, &marker_path)?;
    let marker: serde_json::Value = serde_json::from_slice(&marker_bytes)
        .map_err(|_| "Staging ownership marker was invalid.".to_string())?;
    let directory_id = directory.file_name().and_then(|name| name.to_str());
    if marker["schemaVersion"] != 1
        || marker["owner"] != "nuclear-downloader"
        || marker["operationId"] != expected_operation_id
        || (require_operation_name && directory_id != Some(expected_operation_id))
    {
        return Err("Staging ownership marker was not recognized.".to_string());
    }
    Ok(())
}

fn open_staging_marker(path: &Path) -> Result<std::fs::File, String> {
    let path_metadata = std::fs::symlink_metadata(path)
        .map_err(|_| "Staging folder did not contain an ownership marker.".to_string())?;
    if !path_metadata.is_file() || is_reparse_metadata(&path_metadata) {
        return Err("Staging ownership marker was not a regular non-reparse file.".into());
    }

    let mut options = std::fs::OpenOptions::new();
    options.read(true);
    #[cfg(windows)]
    {
        use std::os::windows::fs::OpenOptionsExt;
        const FILE_SHARE_READ: u32 = 0x0000_0001;
        const FILE_FLAG_OPEN_REPARSE_POINT: u32 = 0x0020_0000;
        options
            .share_mode(FILE_SHARE_READ)
            .custom_flags(FILE_FLAG_OPEN_REPARSE_POINT);
    }
    let file = options
        .open(path)
        .map_err(|_| "Staging folder did not contain an ownership marker.".to_string())?;
    let opened_metadata = file
        .metadata()
        .map_err(|_| "Staging ownership marker could not be inspected.".to_string())?;
    if !opened_metadata.is_file() || is_reparse_metadata(&opened_metadata) {
        return Err("Staging ownership marker was not a regular non-reparse file.".into());
    }
    verify_opened_marker_identity(&file, path)?;
    Ok(file)
}

#[cfg(windows)]
fn verify_opened_marker_identity(opened: &std::fs::File, path: &Path) -> Result<(), String> {
    use std::os::windows::fs::OpenOptionsExt;

    const FILE_SHARE_READ: u32 = 0x0000_0001;
    const FILE_SHARE_WRITE: u32 = 0x0000_0002;
    const FILE_SHARE_DELETE: u32 = 0x0000_0004;
    const FILE_FLAG_OPEN_REPARSE_POINT: u32 = 0x0020_0000;

    fn identity(file: &std::fs::File) -> Result<crate::windows_file::FileIdentity, String> {
        crate::windows_file::identity(file)
            .map_err(|_| "Staging ownership marker identity could not be verified.".to_string())
    }

    let current_metadata = std::fs::symlink_metadata(path)
        .map_err(|_| "Staging ownership marker path changed while it was open.".to_string())?;
    if !current_metadata.is_file() || is_reparse_metadata(&current_metadata) {
        return Err("Staging ownership marker path changed while it was open.".into());
    }
    let mut options = std::fs::OpenOptions::new();
    // This short-lived comparison handle shares all access so it can coexist
    // with the retained writer/delete handle. The retained handle's narrower
    // share mode still prevents external mutation or replacement.
    options
        .read(true)
        .share_mode(FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE)
        .custom_flags(FILE_FLAG_OPEN_REPARSE_POINT);
    let current = options
        .open(path)
        .map_err(|_| "Staging ownership marker path changed while it was open.".to_string())?;
    let current_metadata = current
        .metadata()
        .map_err(|_| "Staging ownership marker path changed while it was open.".to_string())?;
    if !current_metadata.is_file()
        || is_reparse_metadata(&current_metadata)
        || identity(opened)? != identity(&current)?
    {
        return Err("Staging ownership marker path changed while it was open.".into());
    }
    Ok(())
}

#[cfg(unix)]
fn verify_opened_marker_identity(opened: &std::fs::File, path: &Path) -> Result<(), String> {
    use std::os::unix::fs::MetadataExt;

    let current_path_metadata = std::fs::symlink_metadata(path)
        .map_err(|_| "Staging ownership marker path changed while it was open.".to_string())?;
    if !current_path_metadata.is_file() || is_reparse_metadata(&current_path_metadata) {
        return Err("Staging ownership marker path changed while it was open.".into());
    }
    let opened_metadata = opened
        .metadata()
        .map_err(|_| "Staging ownership marker identity could not be verified.".to_string())?;
    let current_metadata = std::fs::metadata(path)
        .map_err(|_| "Staging ownership marker path changed while it was open.".to_string())?;
    if opened_metadata.dev() != current_metadata.dev()
        || opened_metadata.ino() != current_metadata.ino()
    {
        return Err("Staging ownership marker path changed while it was open.".into());
    }
    Ok(())
}

#[cfg(not(any(windows, unix)))]
fn verify_opened_marker_identity(_opened: &std::fs::File, path: &Path) -> Result<(), String> {
    let current_metadata = std::fs::symlink_metadata(path)
        .map_err(|_| "Staging ownership marker path changed while it was open.".to_string())?;
    if !current_metadata.is_file() || is_reparse_metadata(&current_metadata) {
        return Err("Staging ownership marker path changed while it was open.".into());
    }
    Ok(())
}

pub(crate) fn cleanup_abandoned_download_stages(output_roots: &[String]) -> Vec<String> {
    let mut failures = Vec::new();
    for (root_index, output_root) in output_roots.iter().enumerate() {
        if let Err(error) = cleanup_abandoned_download_stages_at(Path::new(output_root)) {
            failures.push(format!("Output root {root_index}: {error}"));
        }
    }
    failures
}

fn cleanup_abandoned_download_stages_at(output_root: &Path) -> Result<(), String> {
    let output_metadata = match std::fs::symlink_metadata(output_root) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(error) => return Err(format!("could not inspect output root ({})", error.kind())),
    };
    if !output_metadata.is_dir() || is_reparse_metadata(&output_metadata) {
        return Err("output root is not a regular non-reparse directory".to_string());
    }
    let output_root = output_root
        .canonicalize()
        .map_err(|error| format!("could not resolve output root ({})", error.kind()))?;
    let staging_root = staging_root(&output_root);
    let staging_metadata = match std::fs::symlink_metadata(&staging_root) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(error) => return Err(format!("could not inspect staging root ({})", error.kind())),
    };
    if !staging_metadata.is_dir() || is_reparse_metadata(&staging_metadata) {
        return Err("staging root is not a regular non-reparse directory".to_string());
    }

    let entries = std::fs::read_dir(&staging_root)
        .map_err(|error| format!("could not enumerate staging root ({})", error.kind()))?;
    for entry in entries {
        let entry =
            entry.map_err(|error| format!("could not inspect staging entry ({})", error.kind()))?;
        let path = entry.path();
        let name = entry.file_name();
        let Some(name) = name.to_str() else {
            continue;
        };
        let operation_id = if uuid::Uuid::parse_str(name).is_ok() {
            name.to_string()
        } else if let Some(rest) = name.strip_prefix(STAGING_CLEANUP_PREFIX) {
            let Some((operation_id, quarantine_id)) = rest.split_once('.') else {
                continue;
            };
            if uuid::Uuid::parse_str(operation_id).is_err()
                || uuid::Uuid::parse_str(quarantine_id).is_err()
            {
                continue;
            }
            operation_id.to_string()
        } else {
            continue;
        };
        let metadata = std::fs::symlink_metadata(&path)
            .map_err(|error| format!("could not inspect staging operation ({})", error.kind()))?;
        if !metadata.is_dir() || is_reparse_metadata(&metadata) {
            continue;
        }
        if verify_staging_marker_with_name_policy(
            &path,
            &operation_id,
            uuid::Uuid::parse_str(name).is_ok(),
        )
        .is_err()
        {
            continue;
        }
        quarantine_and_remove_staging_dir(&staging_root, &path, &operation_id, false)?;
    }
    Ok(())
}

fn is_reparse_metadata(metadata: &std::fs::Metadata) -> bool {
    if metadata.file_type().is_symlink() {
        return true;
    }
    #[cfg(windows)]
    {
        use std::os::windows::fs::MetadataExt;
        const FILE_ATTRIBUTE_REPARSE_POINT: u32 = 0x400;
        metadata.file_attributes() & FILE_ATTRIBUTE_REPARSE_POINT != 0
    }
    #[cfg(not(windows))]
    false
}

#[cfg(windows)]
fn mark_hidden(path: &Path) -> Result<(), String> {
    use std::os::windows::ffi::OsStrExt;
    const FILE_ATTRIBUTE_HIDDEN: u32 = 0x2;
    #[link(name = "Kernel32")]
    extern "system" {
        fn GetFileAttributesW(path: *const u16) -> u32;
        fn SetFileAttributesW(path: *const u16, attributes: u32) -> i32;
    }
    let wide = path
        .as_os_str()
        .encode_wide()
        .chain(Some(0))
        .collect::<Vec<_>>();
    let attributes = unsafe { GetFileAttributesW(wide.as_ptr()) };
    if attributes == u32::MAX
        || unsafe { SetFileAttributesW(wide.as_ptr(), attributes | FILE_ATTRIBUTE_HIDDEN) } == 0
    {
        return Err(format!(
            "Failed to hide staging root: {}",
            std::io::Error::last_os_error()
        ));
    }
    Ok(())
}

#[cfg(not(windows))]
fn mark_hidden(_path: &Path) -> Result<(), String> {
    Ok(())
}

fn validate_staged_file(path: &Path, staging_dir: &Path) -> Result<PathBuf, String> {
    let reported_metadata = std::fs::symlink_metadata(path)
        .map_err(|error| format!("Failed to inspect reported output: {error}"))?;
    if !reported_metadata.file_type().is_file() || reported_metadata.file_type().is_symlink() {
        return Err("Downloader output was not a regular non-reparse file.".to_string());
    }
    #[cfg(windows)]
    {
        use std::os::windows::fs::MetadataExt;
        const FILE_ATTRIBUTE_REPARSE_POINT: u32 = 0x400;
        if reported_metadata.file_attributes() & FILE_ATTRIBUTE_REPARSE_POINT != 0 {
            return Err("Downloader output was a reparse point.".to_string());
        }
    }
    let canonical_stage = staging_dir
        .canonicalize()
        .map_err(|error| format!("Failed to resolve staging folder: {error}"))?;
    let canonical_path = path
        .canonicalize()
        .map_err(|error| format!("Failed to resolve staged output: {error}"))?;
    if canonical_path == canonical_stage || !canonical_path.starts_with(&canonical_stage) {
        return Err("Downloader reported a path outside its staging folder.".to_string());
    }
    let metadata = std::fs::symlink_metadata(&canonical_path)
        .map_err(|error| format!("Failed to inspect staged output: {error}"))?;
    if !metadata.file_type().is_file() || metadata.file_type().is_symlink() {
        return Err("Downloader output was not a regular non-reparse file.".to_string());
    }
    #[cfg(windows)]
    {
        use std::os::windows::fs::MetadataExt;
        const FILE_ATTRIBUTE_REPARSE_POINT: u32 = 0x400;
        if metadata.file_attributes() & FILE_ATTRIBUTE_REPARSE_POINT != 0 {
            return Err("Downloader output was a reparse point.".to_string());
        }
    }
    Ok(canonical_path)
}

pub(super) fn path_to_string(path: &Path) -> String {
    path.to_string_lossy().to_string()
}

pub(super) fn build_webm_final_path(
    request: &DownloadRequest,
    intermediate_path: &Path,
) -> PathBuf {
    let filename = request
        .filename_override
        .as_deref()
        .and_then(normalize_filename_override)
        .or_else(|| {
            intermediate_path
                .file_stem()
                .and_then(|stem| stem.to_str())
                .and_then(sanitize_filename_component)
        })
        .unwrap_or_else(|| "download".to_string());

    PathBuf::from(&request.output_dir).join(format!("{filename}.webm"))
}

pub(super) fn build_staged_webm_output_path(staging_dir: &Path, final_path: &Path) -> PathBuf {
    let stem = final_path
        .file_stem()
        .and_then(|stem| stem.to_str())
        .and_then(sanitize_filename_component)
        .unwrap_or_else(|| "download".to_string());

    staging_dir.join(format!("{stem}.converted.webm"))
}

pub(super) fn build_final_output_path(
    request: &DownloadRequest,
    staged_path: &Path,
) -> Result<PathBuf, String> {
    let file_name = if let Some(filename) = request
        .filename_override
        .as_deref()
        .and_then(normalize_filename_override)
    {
        let extension = staged_path
            .extension()
            .and_then(|value| value.to_str())
            .filter(|value| !value.is_empty())
            .unwrap_or(request.format.as_str());
        format!("{filename}.{extension}").into()
    } else {
        staged_path
            .file_name()
            .ok_or_else(|| "Downloaded file did not have a valid filename.".to_string())?
            .to_os_string()
    };

    Ok(PathBuf::from(&request.output_dir).join(file_name))
}

fn suffixed_output_path(base_path: &Path, suffix: usize) -> PathBuf {
    if suffix <= 1 {
        return base_path.to_path_buf();
    }

    let stem = base_path
        .file_stem()
        .and_then(|value| value.to_str())
        .and_then(sanitize_filename_component)
        .unwrap_or_else(|| "download".to_string());
    let extension = base_path.extension().and_then(|value| value.to_str());
    let filename = match extension {
        Some(extension) if !extension.is_empty() => format!("{stem} ({suffix}).{extension}"),
        _ => format!("{stem} ({suffix})"),
    };

    base_path.with_file_name(filename)
}

pub(super) async fn publish_staged_output(
    staged_output: &Path,
    desired_path: &Path,
    job: Option<&DownloadJob>,
) -> Result<PathBuf, String> {
    validate_publishable_output_path(desired_path)?;
    if let Some(parent) = desired_path.parent() {
        tokio::fs::create_dir_all(parent)
            .await
            .map_err(|error| format!("Failed to create output folder: {error}"))?;
    }

    let staged_file = tokio::fs::OpenOptions::new()
        .read(true)
        .write(true)
        .open(staged_output)
        .await
        .map_err(|error| format!("Failed to open staged output: {error}"))?;
    staged_file
        .sync_all()
        .await
        .map_err(|error| format!("Failed to flush staged output: {error}"))?;
    drop(staged_file);

    for suffix in 1..=MAX_OUTPUT_SUFFIX {
        if job.is_some_and(DownloadJob::is_cancelled) {
            return Err("Publishing was cancelled.".into());
        }

        let candidate = suffixed_output_path(desired_path, suffix);
        validate_publishable_output_path(&candidate)?;
        if candidate.exists() {
            continue;
        }

        match atomic_move_no_replace(staged_output, &candidate).await {
            Ok(()) => {
                return Ok(candidate);
            }
            Err(error)
                if error.kind() == std::io::ErrorKind::AlreadyExists || candidate.exists() =>
            {
                continue
            }
            Err(error) => {
                return Err(format!("Failed to publish output: {error}"));
            }
        }
    }

    Err("Could not allocate a unique output filename.".into())
}

#[cfg(test)]
pub(crate) fn test_create_owned_stage(
    output_root: &Path,
    operation_id: &str,
) -> Result<PathBuf, String> {
    let stage = build_staging_dir(output_root, operation_id);
    reset_staging_dir(&stage, output_root, operation_id)?;
    Ok(stage)
}

#[cfg(test)]
pub(crate) async fn test_publish_staged_file(
    staged_output: &Path,
    desired_path: &Path,
    job: Option<&DownloadJob>,
) -> Result<PathBuf, String> {
    publish_staged_output(staged_output, desired_path, job).await
}

#[cfg(test)]
pub(crate) fn test_cleanup_owned_stage(
    output_root: &Path,
    operation_id: &str,
) -> Result<(), String> {
    cleanup_staging_dir(
        &build_staging_dir(output_root, operation_id),
        output_root,
        operation_id,
    )
}

#[cfg(test)]
pub(crate) fn test_cleanup_abandoned_stages(output_root: &Path) -> Result<(), String> {
    cleanup_abandoned_download_stages_at(output_root)
}

fn validate_publishable_output_path(path: &Path) -> Result<(), String> {
    if path.to_string_lossy().len() > MAX_ACTIONABLE_FIELD_BYTES {
        Err("Published output path exceeds the 4 KiB metadata limit.".to_string())
    } else {
        Ok(())
    }
}

#[cfg(windows)]
async fn atomic_move_no_replace(source: &Path, destination: &Path) -> std::io::Result<()> {
    use std::os::windows::ffi::OsStrExt;
    const MOVEFILE_WRITE_THROUGH: u32 = 0x8;
    #[link(name = "Kernel32")]
    extern "system" {
        fn MoveFileExW(existing: *const u16, new: *const u16, flags: u32) -> i32;
    }
    let source = source
        .as_os_str()
        .encode_wide()
        .chain(Some(0))
        .collect::<Vec<_>>();
    let destination = destination
        .as_os_str()
        .encode_wide()
        .chain(Some(0))
        .collect::<Vec<_>>();
    let moved = unsafe {
        MoveFileExW(
            source.as_ptr(),
            destination.as_ptr(),
            MOVEFILE_WRITE_THROUGH,
        )
    };
    if moved == 0 {
        Err(std::io::Error::last_os_error())
    } else {
        Ok(())
    }
}

#[cfg(not(windows))]
async fn atomic_move_no_replace(source: &Path, destination: &Path) -> std::io::Result<()> {
    tokio::fs::hard_link(source, destination).await?;
    tokio::fs::remove_file(source).await
}

pub(super) fn resolve_staged_output(staging_dir: &Path) -> Result<PathBuf, StagedOutputError> {
    let record_path = final_output_record_path(staging_dir);
    match std::fs::symlink_metadata(&record_path) {
        Ok(metadata) => resolve_recorded_output(&record_path, &metadata, staging_dir),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            resolve_unambiguous_fallback(staging_dir)
        }
        Err(error) => Err(StagedOutputError {
            code: "staging_output_record_invalid",
            message: format!("Failed to inspect downloader output record: {error}"),
        }),
    }
}

fn resolve_recorded_output(
    record_path: &Path,
    metadata: &std::fs::Metadata,
    staging_dir: &Path,
) -> Result<PathBuf, StagedOutputError> {
    if !metadata.file_type().is_file()
        || metadata.file_type().is_symlink()
        || is_reparse_metadata(metadata)
    {
        return Err(StagedOutputError {
            code: "staging_output_record_invalid",
            message: "Downloader output record was not a regular non-reparse file.".to_string(),
        });
    }
    if metadata.len() > MAX_FINAL_OUTPUT_RECORD_BYTES {
        return Err(StagedOutputError {
            code: "staging_output_record_invalid",
            message: format!(
                "Downloader output record exceeded the {MAX_FINAL_OUTPUT_RECORD_BYTES}-byte limit."
            ),
        });
    }

    let mut options = std::fs::OpenOptions::new();
    options.read(true);
    #[cfg(windows)]
    {
        use std::os::windows::fs::OpenOptionsExt;
        const FILE_SHARE_READ: u32 = 0x0000_0001;
        const FILE_FLAG_OPEN_REPARSE_POINT: u32 = 0x0020_0000;
        options
            .share_mode(FILE_SHARE_READ)
            .custom_flags(FILE_FLAG_OPEN_REPARSE_POINT);
    }
    let mut record_file = options
        .open(record_path)
        .map_err(|error| StagedOutputError {
            code: "staging_output_record_invalid",
            message: format!("Failed to read downloader output record: {error}"),
        })?;
    let opened_metadata = record_file.metadata().map_err(|error| StagedOutputError {
        code: "staging_output_record_invalid",
        message: format!("Failed to inspect opened downloader output record: {error}"),
    })?;
    if !opened_metadata.is_file()
        || is_reparse_metadata(&opened_metadata)
        || opened_metadata.len() > MAX_FINAL_OUTPUT_RECORD_BYTES
    {
        return Err(StagedOutputError {
            code: "staging_output_record_invalid",
            message: format!(
                "Downloader output record was not a regular non-reparse file within the {MAX_FINAL_OUTPUT_RECORD_BYTES}-byte limit."
            ),
        });
    }
    let mut contents = Vec::with_capacity(opened_metadata.len() as usize);
    (&mut record_file)
        .take(MAX_FINAL_OUTPUT_RECORD_BYTES + 1)
        .read_to_end(&mut contents)
        .map_err(|error| StagedOutputError {
            code: "staging_output_record_invalid",
            message: format!("Failed to read downloader output record: {error}"),
        })?;
    #[cfg(test)]
    TEST_FINAL_OUTPUT_RECORD_READ_BYTES.with(|bytes| bytes.set(contents.len()));
    if contents.len() as u64 > MAX_FINAL_OUTPUT_RECORD_BYTES {
        return Err(StagedOutputError {
            code: "staging_output_record_invalid",
            message: format!(
                "Downloader output record exceeded the {MAX_FINAL_OUTPUT_RECORD_BYTES}-byte limit."
            ),
        });
    }
    let text = std::str::from_utf8(&contents).map_err(|_| StagedOutputError {
        code: "staging_output_record_invalid",
        message: "Downloader output record was not valid UTF-8.".to_string(),
    })?;
    let mut records = text.lines().filter(|line| !line.trim().is_empty());
    let line = records.next().ok_or_else(|| StagedOutputError {
        code: "staging_output_record_invalid",
        message: "Downloader output record was empty.".to_string(),
    })?;
    if records.next().is_some() {
        return Err(StagedOutputError {
            code: "staging_output_record_invalid",
            message: "Downloader output record contained multiple entries.".to_string(),
        });
    }
    let record: FinalOutputRecord =
        serde_json::from_str(line).map_err(|error| StagedOutputError {
            code: "staging_output_record_invalid",
            message: format!("Downloader output record was malformed: {error}"),
        })?;
    if record.schema_version != 1 {
        return Err(StagedOutputError {
            code: "staging_output_record_invalid",
            message: format!(
                "Downloader output record used unsupported schema version {}.",
                record.schema_version
            ),
        });
    }
    if record.filepath.trim().is_empty() {
        return Err(StagedOutputError {
            code: "staging_output_record_invalid",
            message: "Downloader output record did not contain a filepath.".to_string(),
        });
    }

    validate_staged_file(Path::new(&record.filepath), staging_dir).map_err(|message| {
        StagedOutputError {
            code: "path_escape",
            message,
        }
    })
}

fn resolve_unambiguous_fallback(staging_dir: &Path) -> Result<PathBuf, StagedOutputError> {
    let entries = std::fs::read_dir(staging_dir).map_err(|error| StagedOutputError {
        code: "staging_failed",
        message: format!("Failed to inspect staged downloader output: {error}"),
    })?;
    let mut candidates = Vec::new();
    for entry in entries {
        let entry = entry.map_err(|error| StagedOutputError {
            code: "staging_failed",
            message: format!("Failed to inspect a staged downloader entry: {error}"),
        })?;
        let path = entry.path();
        let extension = path
            .extension()
            .and_then(|extension| extension.to_str())
            .unwrap_or_default()
            .to_ascii_lowercase();
        if !matches!(
            extension.as_str(),
            "mp4"
                | "mkv"
                | "webm"
                | "mov"
                | "m4a"
                | "mp3"
                | "flac"
                | "wav"
                | "aac"
                | "opus"
                | "ogg"
                | "ts"
        ) {
            continue;
        }
        let metadata = std::fs::symlink_metadata(&path).map_err(|error| StagedOutputError {
            code: "staging_failed",
            message: format!("Failed to inspect staged media candidate: {error}"),
        })?;
        if metadata.file_type().is_file()
            && !metadata.file_type().is_symlink()
            && !is_reparse_metadata(&metadata)
        {
            candidates.push(path);
        }
    }

    match candidates.len() {
        0 => Err(StagedOutputError {
            code: "staging_failed",
            message: "Download completed but no staged media file was found.".to_string(),
        }),
        1 => {
            validate_staged_file(&candidates[0], staging_dir).map_err(|message| StagedOutputError {
                code: "path_escape",
                message,
            })
        }
        count => Err(StagedOutputError {
            code: "staging_output_ambiguous",
            message: format!(
                "Download completed without an output record and left {count} staged media files."
            ),
        }),
    }
}

#[cfg(test)]
mod tests {
    use super::super::MAX_ACTIONABLE_FIELD_BYTES;
    use super::{
        append_final_output_record_args, build_staging_dir, build_webm_final_path,
        cleanup_abandoned_download_stages, cleanup_staging_dir, final_output_record_path,
        publish_staged_output, reset_staging_dir, resolve_staged_output, FINAL_OUTPUT_RECORD_NAME,
        STAGING_MARKER_NAME, STAGING_ROOT_NAME,
    };
    use crate::models::DownloadRequest;
    use std::path::{Path, PathBuf};

    fn temp_stage() -> PathBuf {
        let path = std::env::temp_dir().join(format!(
            "nuclear-final-output-record-{}",
            uuid::Uuid::new_v4()
        ));
        std::fs::create_dir(&path).unwrap();
        path
    }

    fn download_request(format: &str, quality: &str) -> DownloadRequest {
        DownloadRequest {
            url: "https://example.com/video".into(),
            quality: quality.into(),
            format: format.into(),
            output_dir: "C:\\Users\\Mr.W\\Downloads".into(),
            cookie_config: None,
            filename_override: None,
            compat_config_path: None,
        }
    }

    fn write_record(stage: &std::path::Path, path: &std::path::Path) {
        let record = serde_json::json!({
            "schema_version": 1,
            "filepath": path.to_string_lossy(),
        });
        std::fs::write(final_output_record_path(stage), format!("{record}\n")).unwrap();
    }

    #[test]
    fn output_record_args_use_after_move_json_and_escape_percent_in_record_path() {
        let stage = PathBuf::from("C:\\Downloads\\100% Ready");
        let mut args = Vec::new();

        append_final_output_record_args(&mut args, &stage);

        assert_eq!(args[0], "--print-to-file");
        assert_eq!(
            args[1],
            r#"after_move:{"schema_version":1,"filepath":%(filepath)j}"#
        );
        assert_eq!(
            args[2],
            format!("C:/Downloads/100%% Ready/{FINAL_OUTPUT_RECORD_NAME}")
        );
    }

    #[test]
    fn machine_record_resolves_the_exact_staged_output() {
        let stage = temp_stage();
        let media = stage.join("chosen.mp4");
        std::fs::write(&media, b"media").unwrap();
        std::fs::write(stage.join("other.txt"), b"not media").unwrap();
        write_record(&stage, &media);

        assert_eq!(
            resolve_staged_output(&stage).unwrap(),
            media.canonicalize().unwrap()
        );
        let _ = std::fs::remove_dir_all(stage);
    }

    #[test]
    fn malformed_present_record_never_uses_fallback() {
        let stage = temp_stage();
        std::fs::write(stage.join("only.mp4"), b"media").unwrap();
        std::fs::write(final_output_record_path(&stage), b"not json\n").unwrap();

        let error = resolve_staged_output(&stage).unwrap_err();

        assert_eq!(error.code, "staging_output_record_invalid");
        assert!(error.message.contains("malformed"));
        let _ = std::fs::remove_dir_all(stage);
    }

    #[test]
    fn stale_small_record_metadata_never_allows_an_unbounded_read() {
        let stage = temp_stage();
        let record_path = final_output_record_path(&stage);
        std::fs::write(&record_path, b"{}\n").unwrap();
        let stale_small_metadata = std::fs::symlink_metadata(&record_path).unwrap();
        let oversized = vec![b' '; super::MAX_FINAL_OUTPUT_RECORD_BYTES as usize + 17];
        std::fs::write(&record_path, &oversized).unwrap();
        super::TEST_FINAL_OUTPUT_RECORD_READ_BYTES.with(|bytes| bytes.set(0));

        let error = super::resolve_recorded_output(&record_path, &stale_small_metadata, &stage)
            .unwrap_err();
        let observed = super::TEST_FINAL_OUTPUT_RECORD_READ_BYTES.with(std::cell::Cell::get);

        assert_eq!(error.code, "staging_output_record_invalid");
        assert!(
            observed <= super::MAX_FINAL_OUTPUT_RECORD_BYTES as usize + 1,
            "record reader consumed {observed} bytes before rejecting its fixed budget"
        );
        assert_eq!(std::fs::read(&record_path).unwrap(), oversized);
        let _ = std::fs::remove_dir_all(stage);
    }

    #[test]
    fn multiple_machine_records_are_rejected_as_ambiguous_authority() {
        let stage = temp_stage();
        let media = stage.join("chosen.mp4");
        std::fs::write(&media, b"media").unwrap();
        let line = serde_json::json!({
            "schema_version": 1,
            "filepath": media.to_string_lossy(),
        });
        std::fs::write(
            final_output_record_path(&stage),
            format!("{line}\n{line}\n"),
        )
        .unwrap();

        let error = resolve_staged_output(&stage).unwrap_err();

        assert_eq!(error.code, "staging_output_record_invalid");
        assert!(error.message.contains("multiple entries"));
        let _ = std::fs::remove_dir_all(stage);
    }

    #[test]
    fn absent_record_accepts_exactly_one_media_candidate() {
        let stage = temp_stage();
        let media = stage.join("only.mkv");
        std::fs::write(&media, b"media").unwrap();
        std::fs::write(stage.join("sidecar.info.json"), b"{}").unwrap();

        assert_eq!(
            resolve_staged_output(&stage).unwrap(),
            media.canonicalize().unwrap()
        );
        let _ = std::fs::remove_dir_all(stage);
    }

    #[test]
    fn absent_record_rejects_multiple_media_candidates_without_mtime_selection() {
        let stage = temp_stage();
        std::fs::write(stage.join("older.mp4"), b"older").unwrap();
        std::fs::write(stage.join("newer.mkv"), b"newer").unwrap();

        let error = resolve_staged_output(&stage).unwrap_err();

        assert_eq!(error.code, "staging_output_ambiguous");
        assert!(error.message.contains("2 staged media files"));
        let _ = std::fs::remove_dir_all(stage);
    }

    #[test]
    fn recorded_output_outside_stage_is_rejected() {
        let stage = temp_stage();
        let outside = stage.parent().unwrap().join(format!(
            "nuclear-outside-output-{}.mp4",
            uuid::Uuid::new_v4()
        ));
        std::fs::write(&outside, b"outside").unwrap();
        write_record(&stage, &outside);

        let error = resolve_staged_output(&stage).unwrap_err();

        assert_eq!(error.code, "path_escape");
        let _ = std::fs::remove_file(outside);
        let _ = std::fs::remove_dir_all(stage);
    }

    #[tokio::test]
    async fn publishing_never_overwrites_and_adds_a_suffix() {
        let root =
            std::env::temp_dir().join(format!("nuclear-publish-test-{}", uuid::Uuid::new_v4()));
        let staging_dir = root.join("staging");
        let output_dir = root.join("output");
        std::fs::create_dir_all(&staging_dir).unwrap();
        std::fs::create_dir_all(&output_dir).unwrap();

        let staged = staging_dir.join("Clip.mp4");
        let desired = output_dir.join("Clip.mp4");
        std::fs::write(&staged, b"new bytes").unwrap();
        std::fs::write(&desired, b"old bytes").unwrap();

        let published = publish_staged_output(&staged, &desired, None)
            .await
            .unwrap();
        assert_eq!(published, output_dir.join("Clip (2).mp4"));
        assert_eq!(std::fs::read(&desired).unwrap(), b"old bytes");
        assert_eq!(std::fs::read(&published).unwrap(), b"new bytes");

        let _ = std::fs::remove_dir_all(root);
    }

    #[tokio::test]
    async fn concurrent_publication_allocates_distinct_names() {
        let root = std::env::temp_dir().join(format!(
            "nuclear-concurrent-publish-test-{}",
            uuid::Uuid::new_v4()
        ));
        let staging_dir = root.join("staging");
        let output_dir = root.join("output");
        std::fs::create_dir_all(&staging_dir).unwrap();
        std::fs::create_dir_all(&output_dir).unwrap();

        let first_staged = staging_dir.join("first.mp4");
        let second_staged = staging_dir.join("second.mp4");
        let desired = output_dir.join("Clip.mp4");
        std::fs::write(&first_staged, b"first").unwrap();
        std::fs::write(&second_staged, b"second").unwrap();

        let (first, second) = tokio::join!(
            publish_staged_output(&first_staged, &desired, None),
            publish_staged_output(&second_staged, &desired, None),
        );
        let mut published = vec![first.unwrap(), second.unwrap()];
        published.sort();

        assert_eq!(
            published,
            vec![output_dir.join("Clip (2).mp4"), output_dir.join("Clip.mp4")]
        );
        let _ = std::fs::remove_dir_all(root);
    }

    #[tokio::test]
    async fn publication_rejects_a_path_that_terminal_metadata_cannot_store() {
        let root = temp_stage();
        let staged = root.join("staged.mp4");
        std::fs::write(&staged, b"staged").unwrap();
        let desired = PathBuf::from("x".repeat(MAX_ACTIONABLE_FIELD_BYTES + 1));

        let error = publish_staged_output(&staged, &desired, None)
            .await
            .unwrap_err();

        assert!(error.contains("4 KiB metadata limit"), "{error}");
        assert!(staged.is_file());
        let _ = std::fs::remove_dir_all(root);
    }

    #[test]
    fn webm_final_path_uses_custom_filename_or_staged_stem() {
        let mut request = download_request("webm", "best");
        request.output_dir = "C:\\Users\\Mr.W\\Desktop".into();
        request.filename_override = Some("Clip: 100%?".into());

        assert_eq!(
            build_webm_final_path(&request, Path::new("C:\\Temp\\ignored.mkv")),
            PathBuf::from("C:\\Users\\Mr.W\\Desktop").join("Clip_ 100%_.webm")
        );

        request.filename_override = None;
        assert_eq!(
            build_webm_final_path(&request, Path::new("C:\\Temp\\Title [abc123].mkv")),
            PathBuf::from("C:\\Users\\Mr.W\\Desktop").join("Title [abc123].webm")
        );
    }

    #[test]
    fn abandoned_stage_cleanup_deletes_only_marker_owned_uuid_directories() {
        let output =
            std::env::temp_dir().join(format!("nuclear-stage-cleanup-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&output).unwrap();
        let valid_id = uuid::Uuid::new_v4().to_string();
        let valid = build_staging_dir(&output, &valid_id);
        reset_staging_dir(&valid, &output, &valid_id).unwrap();
        std::fs::write(valid.join("partial.bin"), b"owned").unwrap();
        let unowned = output
            .join(STAGING_ROOT_NAME)
            .join(uuid::Uuid::new_v4().to_string());
        std::fs::create_dir(&unowned).unwrap();
        std::fs::write(unowned.join("user-file.txt"), b"preserve").unwrap();

        let failures = cleanup_abandoned_download_stages(&[output.to_string_lossy().into_owned()]);

        assert!(failures.is_empty());
        assert!(!valid.exists());
        assert!(unowned.join("user-file.txt").is_file());
        let _ = std::fs::remove_dir_all(output);
    }

    #[test]
    fn active_stage_cleanup_refuses_a_wrong_operation_marker() {
        let output =
            std::env::temp_dir().join(format!("nuclear-stage-marker-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&output).unwrap();
        let operation_id = uuid::Uuid::new_v4().to_string();
        let stage = build_staging_dir(&output, &operation_id);
        reset_staging_dir(&stage, &output, &operation_id).unwrap();
        std::fs::write(stage.join("keep.txt"), b"preserve").unwrap();
        let wrong_marker = serde_json::json!({
            "schemaVersion": 1,
            "owner": "nuclear-downloader",
            "operationId": uuid::Uuid::new_v4().to_string(),
        });
        std::fs::write(
            stage.join(STAGING_MARKER_NAME),
            serde_json::to_vec(&wrong_marker).unwrap(),
        )
        .unwrap();

        assert!(cleanup_staging_dir(&stage, &output, &operation_id).is_err());
        assert!(stage.join("keep.txt").is_file());
        let _ = std::fs::remove_dir_all(output);
    }

    #[cfg(windows)]
    #[test]
    fn marker_initialization_failure_removes_the_empty_new_stage() {
        let output = std::env::temp_dir().join(format!(
            "nuclear-stage-marker-init-failure-{}",
            uuid::Uuid::new_v4()
        ));
        std::fs::create_dir_all(&output).unwrap();
        let operation_id = uuid::Uuid::new_v4().to_string();
        let stage = build_staging_dir(&output, &operation_id);
        super::TEST_MARKER_INITIALIZATION_FAILURE.with(|hook| {
            *hook.borrow_mut() = Some(Box::new(|_| Err("forced marker failure".to_string())));
        });

        let error = reset_staging_dir(&stage, &output, &operation_id).unwrap_err();

        assert!(error.contains("forced marker failure"));
        assert!(
            !stage.exists(),
            "failed initialization left a blocking stage"
        );

        reset_staging_dir(&stage, &output, &operation_id).unwrap();
        assert!(stage.join(STAGING_MARKER_NAME).is_file());
        let _ = std::fs::remove_dir_all(output);
    }

    #[cfg(windows)]
    #[test]
    fn partial_marker_failure_removes_only_the_handle_owned_stage() {
        let output = std::env::temp_dir().join(format!(
            "nuclear-stage-partial-marker-failure-{}",
            uuid::Uuid::new_v4()
        ));
        std::fs::create_dir_all(&output).unwrap();
        let operation_id = uuid::Uuid::new_v4().to_string();
        let stage = build_staging_dir(&output, &operation_id);
        super::TEST_PARTIAL_MARKER_WRITE_FAILURE.with(|failure| failure.set(true));

        let error = reset_staging_dir(&stage, &output, &operation_id).unwrap_err();

        assert!(error.contains("forced partial marker write failure"));
        assert!(
            !stage.exists(),
            "owned partial marker and stage were not rolled back"
        );
        reset_staging_dir(&stage, &output, &operation_id).unwrap();
        assert!(stage.join(STAGING_MARKER_NAME).is_file());
        let _ = std::fs::remove_dir_all(output);
    }

    #[test]
    fn marker_initialization_rollback_preserves_unexpected_content() {
        let output = std::env::temp_dir().join(format!(
            "nuclear-stage-marker-rollback-preserve-{}",
            uuid::Uuid::new_v4()
        ));
        std::fs::create_dir_all(&output).unwrap();
        let operation_id = uuid::Uuid::new_v4().to_string();
        let stage = build_staging_dir(&output, &operation_id);
        super::TEST_MARKER_INITIALIZATION_FAILURE.with(|hook| {
            *hook.borrow_mut() = Some(Box::new(|stage| {
                std::fs::write(stage.join("unexpected.txt"), b"preserve me").unwrap();
                Err("forced marker failure with unexpected content".to_string())
            }));
        });

        let error = reset_staging_dir(&stage, &output, &operation_id).unwrap_err();

        assert!(error.contains("forced marker failure with unexpected content"));
        assert!(error.contains("incomplete staging folder was preserved"));
        assert_eq!(
            std::fs::read(stage.join("unexpected.txt")).unwrap(),
            b"preserve me"
        );
        let _ = std::fs::remove_dir_all(output);
    }

    #[test]
    fn oversized_staging_marker_is_rejected_without_removing_input() {
        let output = std::env::temp_dir().join(format!(
            "nuclear-stage-oversized-marker-{}",
            uuid::Uuid::new_v4()
        ));
        std::fs::create_dir_all(&output).unwrap();
        let operation_id = uuid::Uuid::new_v4().to_string();
        let stage = build_staging_dir(&output, &operation_id);
        reset_staging_dir(&stage, &output, &operation_id).unwrap();
        let marker_path = stage.join(STAGING_MARKER_NAME);
        let mut marker = serde_json::to_vec(&serde_json::json!({
            "schemaVersion": 1,
            "owner": "nuclear-downloader",
            "operationId": operation_id,
        }))
        .unwrap();
        marker.resize(64 * 1024, b' ');
        std::fs::write(&marker_path, &marker).unwrap();

        assert!(super::verify_staging_marker(&stage, &operation_id).is_err());
        assert_eq!(std::fs::read(&marker_path).unwrap(), marker);

        let _ = std::fs::remove_dir_all(output);
    }

    #[cfg(windows)]
    #[test]
    fn active_stage_reset_refuses_a_reparse_staging_root() {
        use std::os::windows::fs::symlink_dir;

        let base =
            std::env::temp_dir().join(format!("nuclear-stage-reparse-{}", uuid::Uuid::new_v4()));
        let output = base.join("output");
        let target = base.join("outside");
        std::fs::create_dir_all(&output).unwrap();
        std::fs::create_dir_all(&target).unwrap();
        let root = output.join(STAGING_ROOT_NAME);
        if symlink_dir(&target, &root).is_err() {
            let _ = std::fs::remove_dir_all(base);
            return;
        }
        let operation_id = uuid::Uuid::new_v4().to_string();
        let stage = root.join(&operation_id);

        assert!(reset_staging_dir(&stage, &output, &operation_id).is_err());
        assert!(target.read_dir().unwrap().next().is_none());

        let _ = std::fs::remove_dir(&root);
        let _ = std::fs::remove_dir_all(base);
    }
}
