// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CookieConfig } from "./CookieConfig";

export type AddQueueItemInput = { inspectionOperationId: string, format: string, quality: string, outputDir: string, cookieConfig?: CookieConfig | null, filenameOverride?: string | null, compatConfigPath?: string | null, };
