// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaylistAdmissionResult } from "./PlaylistAdmissionResult";
import type { QueueItemRecord } from "./QueueItemRecord";

export type AddQueueItemResult = QueueItemRecord | PlaylistAdmissionResult;
