// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable, renderer-safe failure contract for every fallible IPC command.
 *
 * `detail` is optional and must already be redacted by the producer. Raw URLs,
 * cookie material, and full local paths must never be placed in this value.
 */
export type AppError = { code: string, summary: string, detail: string | null, retryable: boolean, correlationId: string, };
