// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationSnapshot } from "./OperationSnapshot";
import type { QueueItemRecord } from "./QueueItemRecord";
import type { RuntimeReadiness } from "./RuntimeReadiness";

export type AppSnapshot = { schemaVersion: number, queue: Array<QueueItemRecord>, operations: Array<OperationSnapshot>, runtimeReadiness: RuntimeReadiness, maintenanceActive: boolean, draining: boolean, latestSequence: number, };
