// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CookieConfig } from "./CookieConfig";
import type { MediaSelection } from "./MediaSelection";

export type BeginInspectionInput = { url: string, cookieConfig?: CookieConfig | null, compatConfigPath?: string | null, selection?: MediaSelection | null, };
