// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloaderRuntimeState } from "./DownloaderRuntimeState";
import type { DownloaderToolStatus } from "./DownloaderToolStatus";

export type DownloaderRuntimeStatus = { state: DownloaderRuntimeState, runtimeVersion: string | null, source: string, updateAvailable: boolean, latestRuntimeVersion: string | null, runtimeDir: string | null, pluginDir: string, message: string | null, tools: Array<DownloaderToolStatus>, };
