// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DownloadProgress = { download_id: string, status: string, progress: number, phase: string | null, download_progress: number | null, conversion_progress: number | null, speed: string | null, eta: string | null, error: string | null, error_code: string | null, error_detail: string | null, filename: string | null, };
