// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DownloaderRuntimeUpdateProgress = { status: string, version: string | null, downloadedBytes: number, totalBytes: number | null, message: string | null, };
