// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CookieConfig } from "./CookieConfig";
import type { MediaSelection } from "./MediaSelection";

export type DownloadRequest = { url: string, quality: string, format: string, output_dir: string, cookie_config?: CookieConfig | null, filename_override?: string | null, compat_config_path?: string | null, selection?: MediaSelection | null, };
