// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OperationKind = "inspection" | "download" | "conversion" | "app_update" | "runtime_update" | "diagnostics_export";
