// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";
import type { OperationKind } from "./OperationKind";
import type { OperationState } from "./OperationState";
import type { UrlInspection } from "./UrlInspection";

export type OperationSnapshot = { schemaVersion: number, id: string, queueItemId: string | null, kind: OperationKind, state: OperationState, progress: number, phase: string | null, sequence: number, createdAtMs: number, updatedAtMs: number, finishedAtMs: number | null, error: AppError | null, inspectionResult: UrlInspection | null, correlationId: string, };
