// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaylistEntry } from "./PlaylistEntry";

export type PlaylistInfo = { title: string, channel: string | null, entry_count: number, truncated: boolean, entries: Array<PlaylistEntry>, };
