// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlaylistEntry = { id: string, title: string | null, duration: number | null, url: string, thumbnail: string | null, };
