// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaylistAdmissionKind } from "./PlaylistAdmissionKind";

export type PlaylistAdmissionResult = { kind: PlaylistAdmissionKind, requestId: string, itemIds: Array<string>, skippedCount: number, };
