// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlaylistAdmissionReceipt = { requestId: string, fingerprint: string, itemIds: Array<string>, skippedCount: number, };
