// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CookieConfig } from "./CookieConfig";
import type { QueueItemState } from "./QueueItemState";

/**
 * Persisted queue configuration. `cookie_config` is an immutable per-item
 * authentication selection containing metadata only; cookie contents are never stored.
 */
export type QueueItemRecord = { schemaVersion: number, id: string, sourceUrl: string, title: string, availableQualities: Array<string>, hasAudio: boolean, cookieConfig: CookieConfig | null, format: string, quality: string, outputDir: string, filenameOverride: string | null, compatConfigPath: string | null, state: QueueItemState, latestOperationId: string | null, createdAtMs: number, updatedAtMs: number, };
