// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RuntimeReadiness = "ready" | "ready_with_warnings" | "repair_required" | "update_available";
