// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationSnapshot } from "./OperationSnapshot";
import type { QueueItemRecord } from "./QueueItemRecord";
import type { RuntimeReadiness } from "./RuntimeReadiness";

export type StateDelta = { schemaVersion: number, sequence: number, emittedAtMs: number, } & ({ "kind": "queue_item_upserted", "value": QueueItemRecord } | { "kind": "queue_items_removed", "value": Array<string> } | { "kind": "operation_upserted", "value": OperationSnapshot } | { "kind": "operation_removed", "value": string } | { "kind": "runtime_readiness_changed", "value": RuntimeReadiness } | { "kind": "maintenance_changed", "value": { active: boolean, draining: boolean, } });
