// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateCheckResult = { currentVersion: string, hasUpdate: boolean, latestVersion: string | null, notes: string | null, publishedAt: string | null, installerName: string | null, };
