// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateQueueItemInput = { format?: string | null, quality?: string | null, outputDir?: string | null, filenameOverride?: string | null, };
