// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaylistInfo } from "./PlaylistInfo";
import type { VideoInfo } from "./VideoInfo";

export type UrlInspection = { "kind": "video", video: VideoInfo, } | { "kind": "playlist", playlist: PlaylistInfo, };
