// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VideoInfo = { id: string, title: string, duration: number | null, channel: string | null, thumbnail: string | null, url: string, available_qualities: Array<string>, has_audio: boolean, };
